{"name": "test_Popuperror_login[logindata0]", "status": "passed", "attachments": [{"name": "log", "source": "11242304-6071-4668-a507-af435fbe0042-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "logindata", "value": "{'usrname': '18938837140', 'passwd': 'python12', 'check': '此账号没有经过授权，请联系管理员!'}"}], "start": 1593615259459, "stop": 1593615260691, "uuid": "cc58175c-6a43-4d80-a0fc-82940f4734b7", "historyId": "c660cc7470264392d3824b575972194e", "testCaseId": "b3330fc0df53c5ec0dd09bda6c1b86f7", "fullName": "TestCases.test_loginTestCases_pytest.Test_LoginCases#test_Popuperror_login", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('refresh_windons')"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_loginTestCases_pytest"}, {"name": "subSuite", "value": "Test_LoginCases"}, {"name": "host", "value": "DESKTOP-IIQKILV"}, {"name": "thread", "value": "30976-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_loginTestCases_pytest"}]}